Переделал хелсчек
KelinNik/ProjectForLearning pull request #11
Opened 2021-08-26 13:58 UTC by KelinNik

Вроде что-то получилось по задачам 
resolves #6
resolves #7

2021-08-27 10:04 UTC, Amaralus requested changes

2021-08-27 10:04 UTC, Amaralus commented on module-a/src/main/java/my/learning/project/appa/controllers/HealthCheckController.java
> +            if (getHChStatusFromModuleB()) {
Логика проверки хелсчека должна быть в сервисе, котнтроллер должен только проксировать вызов в сервис и перехватывать ошибки

2021-08-27 10:04 UTC, Amaralus commented on module-a/src/main/java/my/learning/project/appa/controllers/HealthCheckController.java
> +    private boolean getHChStatusFromModuleB() {
а вот это нужно вынести в отдельный бин AppBHealthchekClient (или как-то так) и потом этот метод должен вызываться в сервисе

2021-08-27 10:04 UTC, Amaralus commented on module-a/src/main/java/my/learning/project/appa/controllers/HealthCheckController.java
> +            HealthCheckStatus healthCheckStatus = restTemplate.getForObject("http://localhost:8082/healthcheckB", HealthCheckStatus.class);
бейсурл приложения Б нужно вынести в проперти и из них, а хчКлиент должен уже добавлять свой доп урл чтобы выйти именно на хч приложения Б

2021-08-30 15:27 UTC, Amaralus requested changes

2021-08-30 15:27 UTC, Amaralus commented on module-a/src/main/java/my/learning/project/appa/clients/AppBHealthCheckClient.java
> +@PropertySource("classpath:env.properties")
Это нужно вешать на Application или на конфигурационный бин (если он есть)

2021-08-30 15:27 UTC, Amaralus commented on module-a/src/main/java/my/learning/project/appa/clients/AppBHealthCheckClient.java
> +@Data
Вообще эта аннотация тут не нужна, так как доступ к переменной за пределами бина не нужен

2021-08-30 15:27 UTC, Amaralus commented on module-a/src/main/java/my/learning/project/appa/clients/AppBHealthCheckClient.java
> +    String baseUrl;
доступ на private, для пропертей инъекция через рефлексию считается приемлемым (в отличие от бинов)

2021-08-30 15:27 UTC, Amaralus commented on module-a/src/main/java/my/learning/project/appa/clients/AppBHealthCheckClient.java
> +            HealthCheckStatus healthCheckStatus = restTemplate.getForObject(baseUrl + "healthcheckB", HealthCheckStatus.class);
не забывай про var из свежей джавы)

2021-08-30 15:27 UTC, Amaralus commented on module-a/src/main/java/my/learning/project/appa/clients/AppBHealthCheckClient.java
> +            log.error("Exception from module B", e);
тут будет правильнее "Ошибка во время запроса статуса ХЧ модуля Б" или в таком духе будет гораздо информативнее

2021-08-30 15:27 UTC, Amaralus commented on module-a/src/main/java/my/learning/project/appa/clients/AppBHealthCheckClient.java
> +                return healthCheckStatus.status;
похоже тут у переменной публичный доступ, это надо исправить (только private, доступ строго через методы)

2021-08-30 15:27 UTC, Amaralus commented on module-a/src/main/java/my/learning/project/appa/controllers/HealthCheckController.java
> +            status = healthCheckService.checkHealthStatus();
переменную можно сразу объявить тут

2021-08-30 15:27 UTC, Amaralus commented on module-a/src/main/java/my/learning/project/appa/services/HealthCheckService.java
> +    private AppBHealthCheckClient appBHealthCheckClient;
final

2021-08-30 15:27 UTC, Amaralus commented on module-a/src/main/java/my/learning/project/appa/services/HealthCheckService.java
> +    String baseUrl;
зачем здесь бейс урл?

2021-08-30 15:27 UTC, Amaralus commented on module-a/src/main/resources/env.properties
> +base.url=http://localhost:8082/
вообще лучше назвать app.b.base.url
просто иначе непонятно это за именно бейс урл

2021-08-31 07:26 UTC, Amaralus commented on module-a/src/main/java/my/learning/project/appa/services/HealthCheckService.java
> +    String baseUrl;
тут он не используется, а если не используется значит надо его убрать

2021-08-31 07:27 UTC, Amaralus requested changes

2021-08-31 07:27 UTC, Amaralus commented on module-a/src/test/java/services/HealthChechTest.java
> +public class HealthChechTest {
Странное название))

2021-08-31 07:33 UTC, KelinNik commented on module-a/src/main/java/my/learning/project/appa/services/HealthCheckService.java
> +    String baseUrl;
Уже убрал

2021-08-31 07:39 UTC, Amaralus approved these changes

2021-08-31 07:53 UTC, merged