Работа с БД
KelinNik/ProjectForLearning pull request #16
Opened 2021-09-12 11:25 UTC by KelinNik

1 Добавил два профиля xml/sql
2 Добавил проверку на коннект к БД в ХЧ

resolve #12

2021-09-13 14:56 UTC, Amaralus requested changes

2021-09-13 14:56 UTC, Amaralus commented on module-b/pom.xml
> +            <scope>runtime</scope>
почему рантайм?

2021-09-13 14:56 UTC, Amaralus commented on module-a/src/main/resources/env.properties
> +#db.url=jdbc:postgresql://localhost:5432/db
почему закоменчено?

2021-09-13 14:56 UTC, Amaralus commented on module-a/src/main/java/my/learning/project/appa/db/DataBaseConnection.java
> +    private static final String URL= "jdbc:postgresql://localhost:5432/db";
урл всегда должен быть в конфигах, его нельзя хардкодить

2021-09-13 14:56 UTC, Amaralus commented on module-a/src/main/java/my/learning/project/appa/db/DataBaseConnection.java
> +public class DataBaseConnection {
реализация очень не правильная, взаимодействие с бд должно быть через хибер и спринг дата, этот файл нужно удалить: задача по ХЧ должна быть отдельной и выполнена после задачи с первым крудом

не мешай задачи в одном пр!

2021-09-13 14:56 UTC, Amaralus commented on module-a/src/main/java/my/learning/project/appa/clients/AppBHealthCheckClient.java
> +            if (healthCheckStatus != null && dataBaseConnection.getConnectionStatuses()) {
эту реализиацию нужно убрать, см комент выше

2021-09-13 14:56 UTC, Amaralus commented on module-a/pom.xml
> +            <scope>runtime</scope>
тот же вопрос про рантайм: зачем?

2021-09-13 14:56 UTC, Amaralus commented on database/changelog/v1/accounts.xml
> +    <changeSet id="1" author="Nick">
сделай ченжсет в sql файле (см DB проект)

2021-09-13 14:56 UTC, Amaralus commented on database/changelog/v1/01-create-account.sql
> +insert into account(first_name, is_active)
проливках таблиц, инсерт данных запрещен, мы обсуждали это

2021-09-13 14:56 UTC, Amaralus commented on database/changelog/v1/01-create-account.sql
> +    account_id  int generated always as identity,
лучше сделать строку аля уникальный никнейм пользователя

2021-09-13 14:56 UTC, Amaralus commented on database/changelog/v1/01-create-account.sql
> +    constraint acc_id unique (account_id)
нужно добавить кнстраит на первичный ключ
+индекс

2021-09-13 14:56 UTC, Amaralus commented on database/changelog/v1/sql-changelog.xml
> +    <include file="accounts.xml" relativeToChangelogFile="true"/>
файл называется sql а ссылается на xml версию, нужно сразу на sql

2021-09-13 14:56 UTC, Amaralus commented on database/pom.xml
> +                            <changeLogFile>changelog/v1/sql-changelog.xml</changeLogFile>
приведи все названия к нормальному виду:
changelog/v1//sql/changelog.xml
changelog/v1//sql/sql-files/account.sql

changelog/v1/xml/changelog.xml
changelog/v1/xml/account.xml

2021-09-14 06:08 UTC, KelinNik commented on module-b/pom.xml
> +            <scope>runtime</scope>
Убрал

2021-09-14 06:12 UTC, KelinNik commented on module-a/src/main/java/my/learning/project/appa/db/DataBaseConnection.java
> +    private static final String URL= "jdbc:postgresql://localhost:5432/db";
Удалил

2021-09-14 06:13 UTC, KelinNik commented on module-a/src/main/java/my/learning/project/appa/db/DataBaseConnection.java
> +public class DataBaseConnection {
Убрал

2021-09-14 06:13 UTC, KelinNik commented on module-a/src/main/java/my/learning/project/appa/clients/AppBHealthCheckClient.java
> +            if (healthCheckStatus != null && dataBaseConnection.getConnectionStatuses()) {
Убрал

2021-09-14 06:14 UTC, KelinNik commented on database/changelog/v1/01-create-account.sql
> +insert into account(first_name, is_active)
Это было для тестирования. Убрал

2021-09-14 06:15 UTC, KelinNik commented on database/changelog/v1/01-create-account.sql
> +    account_id  int generated always as identity,
account_id  serial primary key

2021-09-14 07:26 UTC, KelinNik commented on database/changelog/v1/sql-changelog.xml
> +    <include file="accounts.xml" relativeToChangelogFile="true"/>
Поправил

2021-09-14 07:27 UTC, KelinNik commented on database/pom.xml
> +                            <changeLogFile>changelog/v1/sql-changelog.xml</changeLogFile>
Изменил

2021-09-14 07:28 UTC, KelinNik commented on module-a/src/main/resources/env.properties
> +#db.url=jdbc:postgresql://localhost:5432/db
Почему-то не хотело работать из properties

2021-09-15 10:26 UTC, Amaralus requested changes

2021-09-15 10:26 UTC, Amaralus commented on database/pom.xml
> +            <groupId>sbrf.liquibase</groupId>
sbrf зависимость надо убрать

2021-09-15 10:26 UTC, Amaralus commented on database/pom.xml
> +            <scope>runtime</scope>
рантаймы надо убрать везде

2021-09-15 10:26 UTC, Amaralus commented on database/pom.xml
> +                            <id>initial_setup</id>
копипаста?

2021-09-15 10:26 UTC, Amaralus commented on database/changelog/v1/sql/changelog.xml
> +    <changeSet id="1" author="Nick">
нужно переделать на sql формат ченжсета

2021-09-15 10:26 UTC, Amaralus commented on database/changelog/v1/sql/accounts.sql
> +    account_id  serial primary key,
нужна строка так как акаунт айди это никнейм, так указано в таске

2021-09-15 10:26 UTC, Amaralus commented on database/changelog/v1/sql/accounts.sql
> +    is_active   bool,
зачем тут это поле?

2021-09-15 10:26 UTC, Amaralus commented on database/changelog/v1/sql/accounts.sql
> +    account_id  serial primary key,
например в телеге у тебя есть никнейм и отдельно имя фамилия

2021-09-15 10:28 UTC, KelinNik commented on database/changelog/v1/01-create-account.sql
> +    constraint acc_id unique (account_id)
Добавил индекс.

2021-09-15 10:31 UTC, KelinNik commented on database/pom.xml
> +            <groupId>sbrf.liquibase</groupId>
как ты его там разглядел ))

2021-09-15 10:32 UTC, KelinNik commented on database/pom.xml
> +            <scope>runtime</scope>
убрал

2021-09-15 10:33 UTC, KelinNik commented on database/pom.xml
> +                            <id>initial_setup</id>
конечно ))

2021-09-15 10:35 UTC, KelinNik commented on database/changelog/v1/sql/accounts.sql
> +    is_active   bool,
убрал

2021-09-15 11:03 UTC, KelinNik commented on database/changelog/v1/sql/changelog.xml
> +    <changeSet id="1" author="Nick">
переделал

2021-09-15 11:09 UTC, Amaralus requested changes

2021-09-15 11:09 UTC, Amaralus commented on database/changelog/v1/sql/changelog.xml
> +    <changeSet id="1" author="Nick">
ты xml  переделал в sql, а надо было этот переделать

2021-09-15 11:32 UTC, Amaralus approved these changes

2021-09-15 11:34 UTC, merged