Добавил CRUD операции в модуль B
KelinNik/ProjectForLearning pull request #17
Opened 2021-09-19 16:32 UTC by KelinNik

А так же добавил немного custom exceptions

resolve #13

2021-09-23 11:03 UTC, Amaralus requested changes
Остальное разберем на вантуван

2021-09-23 11:03 UTC, Amaralus commented on module-b/src/main/java/my/learning/project/appb/mapper/AccountMapper.java
> +    AccountMapper MAPPER = Mappers.getMapper(AccountMapper.class);
переделай маппер, так чтобы он стал бином спринга (в аннотации поправить) и потом подключай как бин

2021-09-23 11:03 UTC, Amaralus commented on module-b/src/main/java/my/learning/project/appb/dto/AccountDto.java
> +    private String accountId;
Добавь валидации для этого дто (аннотации), и проверку на контроллере + перехват ошибики валидации
аккаунт айди - обязательное поле, над остальными подумай с точки зрения мессенджера

2021-09-23 11:03 UTC, Amaralus commented on module-b/src/main/java/my/learning/project/appb/services/AccountService.java
> +    AccountRepository accountRepository;
почему package-private?

2021-09-23 11:03 UTC, Amaralus commented on module-b/src/main/java/my/learning/project/appb/exceptions/CustomExceptionHandler.java
> +                HttpStatus.I_AM_A_TEAPOT);
зачем чайник?

2021-10-03 15:42 UTC, KelinNik commented on module-b/src/main/java/my/learning/project/appb/mapper/AccountMapper.java
> +    AccountMapper MAPPER = Mappers.getMapper(AccountMapper.class);
Поправил

2021-10-03 15:42 UTC, KelinNik commented on module-b/src/main/java/my/learning/project/appb/dto/AccountDto.java
> +    private String accountId;
Вроде что-то получилось сделать

2021-10-03 15:43 UTC, KelinNik commented on module-b/src/main/java/my/learning/project/appb/services/AccountService.java
> +    AccountRepository accountRepository;
Проглядел, поправил

2021-10-03 15:43 UTC, KelinNik commented on module-b/src/main/java/my/learning/project/appb/exceptions/CustomExceptionHandler.java
> +                HttpStatus.I_AM_A_TEAPOT);
Шутки ради )) Убрал

2021-10-20 11:41 UTC, Amaralus requested changes
Все херня - давай по новой

2021-10-20 11:41 UTC, Amaralus commented on database/changelog/v1/sql/accounts.sql
> +create table if not exists accountModel
таблица должна называться аккаунт

2021-10-20 11:41 UTC, Amaralus commented on module-b/src/main/java/my/learning/project/appb/configuration/SpringConfig.java
> +    public  AccountMapper accountMapper(){
бин должен создаваться не так, читай подробнее доку мапстракта + пример у нас в коде

2021-10-20 11:41 UTC, Amaralus commented on module-b/src/main/java/my/learning/project/appb/database/model/AccountModel.java
> +@Getter
проще сразу использовать аннтацию дата

2021-10-20 11:41 UTC, Amaralus commented on module-b/src/main/java/my/learning/project/appb/mapper/AccountMapper.java
> +@Component
не корректное использование бина

2021-10-20 11:41 UTC, Amaralus commented on module-b/src/main/java/my/learning/project/appb/exceptions/CustomExceptionHandler.java
> +    private static final Map<String, String> STATUS_MESSAGE_MAP = ImmutableMap.<String, String>builder()
вместо иммутейбл мап используй java.util.Map.of

2021-10-20 11:41 UTC, Amaralus commented on module-b/src/main/java/my/learning/project/appb/services/AccountService.java
> +    public AccountModel createAccount(Account account) {
лучше переименовать в save

2021-10-20 11:41 UTC, Amaralus commented on module-b/src/main/java/my/learning/project/appb/services/AccountService.java
> +        } catch (Exception ignored) {
там есть конкртеный экспешн который нужно прехватить, если перехватытвать все, то можно пропустить значимую ошибку + так же нужно поменять текст на варн лог о том что нельзя удалить того чего нет

2021-10-20 11:41 UTC, Amaralus commented on module-b/src/main/java/my/learning/project/appb/services/AccountService.java
> +        } catch (Exception ignored) {
EmptyResultDataAccessException

2021-10-20 11:41 UTC, Amaralus commented on module-b/src/test/java/my/learning/project/appb/AccountServiceTest.java
> +    private Account account;
аккаунт нужно создавать самому, он не дожен быть бином

2021-10-20 11:41 UTC, Amaralus commented on module-b/src/main/java/my/learning/project/appb/dto/Account.java
> +@Component
модель не может быть бином!

2021-10-20 11:41 UTC, Amaralus commented on module-b/src/test/java/my/learning/project/appb/AccountServiceTest.java
> +        assertEquals("111", accountRepository.getById(accountModel.getAccountId()).getAccountId());
ищи один раз вместо 3х

2021-10-20 11:41 UTC, Amaralus commented on module-b/src/test/java/my/learning/project/appb/AccountServiceTest.java
> +        assertEquals("FF", accountRepository.getById(ff.getAccountId()).getAccountId());
некорректные ассерты
ты должен сравнивать фф с тем что в модели, а не искать 3 раза и сравнивать с текстом

2021-10-20 11:41 UTC, Amaralus commented on module-b/src/test/java/my/learning/project/appb/AccountServiceTest.java
> +    void checkUpdateAccountPositive() {
апдейт это сейв, добавить в модель другие данные и сейв
а потом  поиск и сравнение с моделью
передалеать

2021-10-20 11:41 UTC, Amaralus commented on module-b/src/test/java/my/learning/project/appb/AccountServiceTest.java
> +    void checkDeleteAccountPositive() {
arrange - assert - act - assert 
wtf??

2021-10-20 11:41 UTC, Amaralus commented on module-b/src/test/java/my/learning/project/appb/AccountServiceTest.java
> +    void checkDeleteAccountPositive() {
проверка на удаление это сейв - делит - найти проверить что результат налл или эксепшн как у тебя

2021-10-20 11:41 UTC, Amaralus commented on module-b/src/test/java/my/learning/project/appb/AccountServiceTest.java
> +    void checkCreateAccountNegative() {
этот тест не нужен, ошибки отработает перехватчик ошибок

2021-10-27 12:31 UTC, KelinNik commented on database/changelog/v1/sql/accounts.sql
> +create table if not exists accountModel
Исправил

2021-10-27 12:31 UTC, KelinNik commented on module-b/src/main/java/my/learning/project/appb/configuration/SpringConfig.java
> +    public  AccountMapper accountMapper(){
Исправил

2021-10-27 12:33 UTC, KelinNik commented on module-b/src/main/java/my/learning/project/appb/database/model/AccountModel.java
> +@Getter
CodeStyle ругается...

2021-10-27 12:33 UTC, KelinNik commented on module-b/src/main/java/my/learning/project/appb/mapper/AccountMapper.java
> +@Component
Убрал

2021-10-27 12:33 UTC, KelinNik commented on module-b/src/main/java/my/learning/project/appb/exceptions/CustomExceptionHandler.java
> +    private static final Map<String, String> STATUS_MESSAGE_MAP = ImmutableMap.<String, String>builder()
Поправили

2021-10-27 12:33 UTC, KelinNik commented on module-b/src/test/java/my/learning/project/appb/AccountServiceTest.java
> +        assertEquals("111", accountRepository.getById(accountModel.getAccountId()).getAccountId());
Исправил

2021-10-27 12:33 UTC, KelinNik commented on module-b/src/test/java/my/learning/project/appb/AccountServiceTest.java
> +        assertEquals("FF", accountRepository.getById(ff.getAccountId()).getAccountId());
Исправил

2021-10-27 12:34 UTC, KelinNik commented on module-b/src/test/java/my/learning/project/appb/AccountServiceTest.java
> +    void checkUpdateAccountPositive() {
Готово

2021-10-27 12:34 UTC, KelinNik commented on module-b/src/test/java/my/learning/project/appb/AccountServiceTest.java
> +    void checkDeleteAccountPositive() {
поправил

2021-10-27 12:35 UTC, KelinNik commented on module-b/src/test/java/my/learning/project/appb/AccountServiceTest.java
> +    void checkCreateAccountNegative() {
убрал

2021-10-27 13:11 UTC, KelinNik commented on module-b/src/main/java/my/learning/project/appb/services/AccountService.java
> +    public AccountModel createAccount(Account account) {
done

2021-10-27 13:12 UTC, KelinNik commented on module-b/src/main/java/my/learning/project/appb/services/AccountService.java
> +        } catch (Exception ignored) {
done

2021-10-27 13:15 UTC, Amaralus approved these changes

2021-10-27 13:15 UTC, merged